apiVersion: v1
kind: Service
metadata:
  name: tezos-bootstrap-node-rpc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - nodePort: 31732
      port: 8732
  selector:
    app: tezos-bootstrap-node
  type: NodePort
---
{{- if not .Values.zerotier_in_use }}
apiVersion: v1
kind: Service
metadata:
  name: tezos-bootstrap-node-p2p
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - nodePort: 30732
      port: 9732
  selector:
    app: tezos-bootstrap-node
  type: NodePort
---
{{ end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tezos-bootstrap-node-pv-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "15Gi"
