apiVersion: v1
kind: PersistentVolume
metadata:
  name: tezos-var-volume
  labels:
    storage-type: var-files
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
