apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerotier-pv-claim
  namespace: "tqtezos"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zerotier-config
  namespace: "tqtezos"
data:
  NETWORK_IDS: "17d709436c58c5a2"
  ZTAUTHTOKEN: "mrdtYv0hXb42MldaZdoE5ZcnyFP6D0g2"
  AUTOJOIN: "true"
  ZTHOSTNAME: "idtJTEwNtc1XMuUSdD6i4uamWuE5cB"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zerotier-bridge
  namespace: "tqtezos"
spec:
  selector:
    matchLabels:
      name: zerotier-one
  template:
    metadata:
      labels:
        name: zerotier-one
    spec:
      hostNetwork: true
      containers:
      - name: zerotier-bridge
        image: tqasmith/zerotier-k8s:latest
        env:
        - name: NETWORK_IDS
          valueFrom:
            configMapKeyRef:
              name: zerotier-config
              key: NETWORK_IDS
        - name: ZTHOSTNAME
          valueFrom:
            configMapKeyRef:
              name: zerotier-config
              key: ZTHOSTNAME
        - name: ZTAUTHTOKEN
          valueFrom:
            configMapKeyRef:
              name: zerotier-config
              key: ZTAUTHTOKEN
        - name: AUTOJOIN
          valueFrom:
            configMapKeyRef:
              name: zerotier-config
              key: AUTOJOIN
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "NET_RAW","SYS_ADMIN"]
        volumeMounts:
        - name: dev-net-tun
          mountPath: /dev/net/tun
        - name: ztdata
          mountPath: /var/lib/zerotier-one
      volumes:
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
      - name: ztdata
        persistentVolumeClaim:
          claimName: zerotier-pv-claim
