baker: true
chain_name: YOUR_CHAIN_NAME_HERE
is_invitation: false
rpc_auth: false
chain_type: public
network: edo2net
zerotier_config:
  zerotier_network: YOUR_NETWORK_ID_HERE
  zerotier_token: YOUR_ZEROTIER_TOKEN_HERE

# Images not part of the tezos-k8s repo go here
images:
  tezos: v8-release
# Images that are part of the tezos-k8s repo go here
tezos_k8s_images:
  baker_endorser: tezos-k8s-baker-endorser:dev
  chain_initiator: tezos-k8s-chain-initiator:dev
  config_generator: tezos-k8s-config-generator:dev
  wait_for_bootstrap: tezos-k8s-wait-for-bootstrap:dev
  zerotier: tezos-k8s-zerotier:dev
  snapshot_downloader: tezos-k8s-snapshot-downloader:dev

snapshot_url: https://mainnet.xtz-shots.io/rolling
protocol:
  bootstrap_mutez: "4000000000000"
  hash: PtEdo2ZkT9oKpimTah6x2embF25oss54njMuPzkJTEi5RqfdZFA
  command: 008-PtEdo2Zk
genesis:
  block: "YOUR_GENESIS_CHAIN_ID_HERE"
  timestamp:  '2021-02-12T17:02:24.061398+00:00'
bootstrap_peers: []
accounts:
   - name: baker0
nodes:
  baking:
  - {}
  regular:
  - {}
# TODO
# archive nodes, node with open rpc
# take into account fundraisers accounts that people need to activate
