chain_name: YOUR_CHAIN_NAME_HERE
is_invitation: false
rpc_auth: false

# Chain type options: isolated, private, public
chain_type: isolated
# A chain using Zerotier would be a private chain
zerotier_config:
  zerotier_network: YOUR_NETWORK_ID_HERE
  zerotier_token: YOUR_ZEROTIER_TOKEN_HERE

# Images not part of the tezos-k8s repo go here
images:
  tezos: tezos/tezos:v8-release
# Images that are part of the tezos-k8s repo go here with 'dev' tag
tezos_k8s_images:
  baker_endorser: tezos-k8s-baker-endorser:dev
  chain_initiator: tezos-k8s-chain-initiator:dev
  config_generator: tezos-k8s-config-generator:dev
  wait_for_bootstrap: tezos-k8s-wait-for-bootstrap:dev
  zerotier: tezos-k8s-zerotier:dev
  snapshot_downloader: tezos-k8s-snapshot-downloader:dev

snapshot_url: https://mainnet.xtz-shots.io/rolling
protocol:
  # The defualt mutez given to an account if account is not provided
  bootstrap_mutez: "4000000000000"
  hash: PtEdo2ZkT9oKpimTah6x2embF25oss54njMuPzkJTEi5RqfdZFA
  command: 008-PtEdo2Zk
genesis:
  block: "YOUR_GENESIS_CHAIN_ID_HERE"
  timestamp: "2021-02-12T17:02:24.061398+00:00"
bootstrap_peers: []
# TODO
# archive nodes, node with open rpc
# take into account fundraisers accounts that people need to activate

# Properties that are templated in Helm template files
baker_statefulset: # charts/tezos/templates/baker.yaml
  name: tezos-baking-node
regular_node_statefulset: # charts/tezos/templates/node.yaml
  name: tezos-node

accounts:
 tqtezos_baker_0:
    key: edsk...
    type: secret
    is_bootstrap_baker_account: true
    bootstrap_balance: 50000000000000
 tqtezos_baker_1:
    key: edsk...
    type: secret
    is_bootstrap_baker_account: true
    bootstrap_balance: 4000000000000
  tqtezos_node_0:
    key: edsk...
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: 4000000000000


# Names of nodes should be consistent with the above statefulset names but with
# an added suffix being the index of the node. These names with suffix are the
# `metadata.name` of the downward k8s API. They should be kebab case.
# https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
nodes:
  baking:
    tezos-baking-node-0:
      bake_using_account: tqtezos_baker_0
      bootstrap: true
      history_mode: archive
  regular:
    tezos-node-0:
      bake_using_account: tqtezos_baker_1
      history_mode: archive

protocol_parameters:
  preserved_cycles: 2
  blocks_per_cycle: 8
  blocks_per_commitment: 4
  blocks_per_roll_snapshot: 4
  blocks_per_voting_period: 64
  time_between_blocks: ["10", "20"]
  endorsers_per_block: 32
  hard_gas_limit_per_operation: "800000"
  hard_gas_limit_per_block: "8000000"
  proof_of_work_threshold: "-1"
  tokens_per_roll: "8000000000"
  michelson_maximum_type_size: 1000
  seed_nonce_revelation_tip: "125000"
  origination_size: 257
  block_security_deposit: "512000000"
  endorsement_security_deposit: "64000000"
  endorsement_reward: ["2000000"]
  cost_per_byte: "1000"
  hard_storage_limit_per_operation: "60000"
  test_chain_duration: "1966080"
  quorum_min: 2000
  quorum_max: 7000
  min_proposal_quorum: 500
  initial_endorsers: 1
  delay_per_missing_endorsement: "1"
  baking_reward_per_endorsement: ["200000"]
