apiVersion: batch/v1
kind: Job
metadata:
  name: activate-job
  namespace: "tqtezos"
spec:
  template:
    metadata:
      name: activate-job
    spec:
      containers:
      - name: activate
        image: tezos/tezos:v7-release
        command: ["/usr/local/bin/tezos-client"]
        args: ["-A", "tezos-rpc", "-P", "8732", "-d", "/var/tezos/client", "-l", "--block", "genesis", "activate", "protocol", "PsCARTHAGazKbHtnKfLzQg3kms52kSRpgnDY982a9oYsSXRLQEb", "with", "fitness", "25", "and", "key", "genesis", "and", "parameters", "/etc/tezos/parameters.json"
]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: tezos-config
      - name: var-volume
        persistentVolumeClaim:
          claimName: tezos-pv-claim
