apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-endorser
  namespace: "tqtezos"
spec:
  selector:
    matchLabels:
      app: tezos-endorser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-endorser
    spec:
      containers:
      - image: {docker_image}
        imagePullPolicy: Always
        name: tezos-endorser
        command: [{endorser_command}]
        args: ["-A", "tezos-rpc", "-P", "8732", "-d", "/var/tezos/client", "--chain", {chain_name}, "run", "baker"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      volumes:
      - name: config-volume
        configMap:
          name: tezos-config
      - name: var-volume
        persistentVolumeClaim:
          claimName: tezos-pv-claim
