apiVersion: v1
kind: Service
metadata:
  name: tezos-rpc
  namespace: "tqtezos"
spec:
  ports:
  - port: 8732
  selector:
    app: tezos-node
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-net
  namespace: "tqtezos"
spec:
  ports:
  - port: 9732
  selector:
    app: tezos-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-node
  namespace: "tqtezos"
spec:
  selector:
    matchLabels:
      app: tezos-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-node
    spec:
      initContainers:
      - name: identity-job
        image: {docker_image}
        command: ["/usr/local/bin/tezos-node"]
        args: ["identity", "generate", "0", "--data-dir", "/var/tezos/node", "--config-file", "/etc/tezos/config.json"
]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      containers:
      - image: {docker_image}
        imagePullPolicy: Always
        name: tezos-node
        command: ["/usr/local/bin/tezos-node"]
        args: ["run", "--config-file",  "/etc/tezos/config.json"]
        readinessProbe:
          exec:
            command: ["nc", "-z", "127.0.0.1", "8732"]
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 1
        ports:
        - containerPort: 8732
          name: tezos-rpc
        - containerPort: 9732
          name: tezos-net
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      volumes:
      - name: config-volume
        configMap:
          name: tezos-config
      - name: var-volume
        persistentVolumeClaim:
          claimName: tezos-pv-claim
