apiVersion: v1
kind: PersistentVolume
metadata:
  name: tezos-var-volume
  labels:
    storage-type: var-files
spec:
  storageClassName: standard
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {tezos_dir}
