apiVersion: v1
data:
  CHAIN_PARAMS: |
    {
      "bootstrap_peers": {{ toJson .Values.bootstrap_peers }},
      "chain_type": "{{ .Values.chain_type }}",
      "defualt_bootstrap_mutez": "{{ .Values.bootstrap_mutez }}",
      "expected-proof-of-work": {{ toJson .Values.expected_proof_of_work }},

      "full_snapshot_url": {{ toJson .Values.full_snapshot_url }},
      "rolling_snapshot_url": {{ toJson .Values.rolling_snapshot_url }},

      "network": {{ toJson .Values.node_config_network }},
      "proto_command": "{{ .Values.protocol.command }}",
      "protocol_hash": {{ toJson .Values.activation.protocol_hash }},
      "protocol_parameters": {{ toJson .Values.protocol_parameters }}
    }
  NODES: |
{{ .Values.nodes | toJson | indent 4}}
kind: ConfigMap
metadata:
  name: tezos-config
  namespace: {{ .Release.Namespace }}
---
{{- if eq .Values.chain_type "private" }}
apiVersion: v1
data:
  CHAIN_NAME: "{{ .Values.node_config_network.chain_name }}"
  NETWORK_ID: "{{ .Values.zerotier_config.zerotier_network }}"
  ZTAUTHTOKEN: "{{ .Values.zerotier_config.zerotier_token }}"
  NODES: |
{{ .Values.nodes | toJson | indent 4}}
kind: ConfigMap
metadata:
  name: zerotier-config
  namespace: {{ .Release.Namespace }}
---
{{- end}}
apiVersion: v1
data:
  ACCOUNTS: |
{{ .Values.accounts | toJson | b64enc | indent 4 }}
kind: Secret
metadata:
  name: tezos-secret
  namespace: {{ .Release.Namespace }}
