apiVersion: v1
data:
  CHAIN_PARAMS: |
    {
      "bootstrap_peers": {{ toJson .Values.bootstrap_peers }},
      "chain_type": "{{ .Values.chain_type }}",
      "default_bootstrap_mutez": "{{ .Values.bootstrap_mutez }}",
      "expected-proof-of-work": {{ toJson .Values.expected_proof_of_work }},

      "full_snapshot_url": {{ toJson .Values.full_snapshot_url }},
      "rolling_snapshot_url": {{ toJson .Values.rolling_snapshot_url }},

      "network": {{ mustToPrettyJson .Values.node_config_network | indent 8 | trim }},
      "proto_command": "{{ .Values.protocol.command }}",
      {{- $activation := .Values.activation | default dict }}
      "protocol_activation": {{ mustToPrettyJson $activation | indent 8 | trim }}
    }
  NODES: |
{{ .Values.nodes | mustToPrettyJson | indent 4 }}
kind: ConfigMap
metadata:
  name: tezos-config
  namespace: {{ .Release.Namespace }}
---
{{- if (include "tezos.isThereZerotierConfig" .) }}
apiVersion: v1
data:
  CHAIN_NAME: "{{ .Values.node_config_network.chain_name }}"
  NETWORK_ID: "{{ .Values.zerotier_config.zerotier_network }}"
  ZTAUTHTOKEN: "{{ .Values.zerotier_config.zerotier_token }}"
  NODES: |
{{ .Values.nodes | mustToPrettyJson | indent 4 }}
kind: ConfigMap
metadata:
  name: zerotier-config
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: v1
data:
  ACCOUNTS: |
{{ .Values.accounts | toJson | b64enc | indent 4 }}
kind: Secret
metadata:
  name: tezos-secret
  namespace: {{ .Release.Namespace }}
