apiVersion: v1
data:
  CHAIN_PARAMS: |
    {
      "defualt_bootstrap_mutez": "{{ .Values.protocol.bootstrap_mutez }}",
      "bootstrap_peers": {{ toJson .Values.bootstrap_peers }},
      "nodes": {{ toJson .Values.nodes }},
      "chain_name": "{{ .Values.chain_name }}",
      "protocol_parameters": "{{ omit .Values.protocol_parameters "bootstrap_accounts" }}",
      "genesis_block": "{{ .Values.genesis.block }}",
      "timestamp": "{{ .Values.genesis.timestamp }}",
      "activation_account": "{{ (index .Values.protocol_parameters.bootstrap_accounts 0).name }}",
      "zerotier_in_use": {{ .Values.zerotier_in_use }},
      "proto_command": "{{ .Values.protocol.command }}",
      "protocol_hash": "{{ .Values.protocol.hash }}"
    }
  NODES: |
{{ .Values.nodes | toJson | indent 4}}
kind: ConfigMap
metadata:
  name: tezos-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  CHAIN_NAME: "{{ .Values.chain_name }}"
  NETWORK_ID: "{{ .Values.zerotier_config.zerotier_network }}"
  ZTAUTHTOKEN: "{{ .Values.zerotier_config.zerotier_token }}"
  NODES: |
{{ .Values.nodes | toJson | indent 4}}
kind: ConfigMap
metadata:
  name: zerotier-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  ACCOUNTS: |
{{ .Values.protocol_parameters.bootstrap_accounts | toJson | b64enc | indent 4 }}
kind: Secret
metadata:
  name: tezos-secret
  namespace: {{ .Release.Namespace }}
