{{- range $key, $val := .Values.signers }}
{{- if $val }}
  {{- $_ := set $ "node_class" $key }}
  {{- $_ := set $ "node_vals" $val }}
  {{- $_ := set $ "node_identities" dict }}
  {{- $_ := set $ "pod_type" "signing" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.node_class }}
  namespace: {{ $.Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ $.node_vals.instances | len }}
  serviceName: {{ $.node_class }}
  selector:
    matchLabels:
      node_class: {{ $.node_class }}
  template:
    metadata:
      labels:
        appType: tezos-signer
        node_class: {{ $.node_class }}
    spec:
      containers:
        {{- include "tezos.container.signer"      $ | indent 8 }}
      initContainers:
        {{- include "tezos.init_container.config_generator"    $ | indent 8 }}
      securityContext:
        fsGroup: 100
      volumes:
        - emptyDir: {}
          name: var-volume
        - name: tezos-accounts
          secret:
            secretName: tezos-secret
      securityContext:
        fsGroup: 100
      volumes:
        - emptyDir: {}
          name: var-volume
        - emptyDir: {}
          name: config-volume
        - name: tezos-accounts
          secret:
            secretName: tezos-secret
---
{{- end }}
{{- end }}
