{{- $tezosK8sSigners := get (include "tezos.getRemoteSigners" . | fromJson) "tezosK8sSigners" }}
{{- if and (not .Values.is_invitation) (len $tezosK8sSigners) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tezos_k8s_signer_statefulset.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: 6732
      name: signer
  selector:
    app: {{ .Values.tezos_k8s_signer_statefulset.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.tezos_k8s_signer_statefulset.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ len $tezosK8sSigners }}
  serviceName: {{ .Values.tezos_k8s_signer_statefulset.name }}
  selector:
    matchLabels:
      app: {{ .Values.tezos_k8s_signer_statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tezos_k8s_signer_statefulset.name }}
    spec:
      containers:
      - name: tezos-signer
        image: "{{ .Values.images.octez }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6732
          name: signer
        command:
          - /bin/sh
        volumeMounts:
        - mountPath: /var/tezos
          name: var-volume
        args:
          - "-c"
          - |
{{ tpl (.Files.Get "scripts/remote-signer.sh") $ | indent 12 }}
      initContainers:
      - image: {{ .Values.tezos_k8s_images.utils }}
        imagePullPolicy: IfNotPresent
        name: config-generator
        args:
          - "config-generator"
        envFrom:
          - configMapRef:
              name: tezos-config
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_TYPE
            value: {{ .Values.tezos_k8s_signer_statefulset.pod_type }}
        volumeMounts:
          - mountPath: /var/tezos
            name: var-volume
          - mountPath: /etc/secret-volume
            name: tezos-accounts
      securityContext:
        fsGroup: 100
      volumes:
        - emptyDir: {}
          name: var-volume
        - name: tezos-accounts
          secret:
            secretName: tezos-secret
---
{{- end }}
