version: v1beta9
deployments:
  - name: rpc-auth
    namespace: tqtezos
    kubectl:
      manifests:
        - ../../tqchain/deployment/rpc-auth.yaml
images:
  rpc-auth:
    image: tezos-rpc-auth
    dockerfile: ./Dockerfile
    context: ./
    build:
      docker:
        options:
          buildArgs:
            FLASK_ENV: ${FLASK_ENV}
dev:
  logs:
    images:
      - rpc-auth
  sync:
    - imageName: rpc-auth
      namespace: tqtezos
      labelSelector:
        app: rpc-auth
      localSubPath: ./server
  autoReload:
    images:
      - rpc-auth
    deployments:
      - rpc-auth
    # paths:
    #   - ./tqchain/deployment/*
hooks:
  # - command: sh
  #   args:
  #     - -c
  #     - "mkchain ${ACTION} ${CHAIN_NAME} > ../mkchain-devspace.yaml"
    # when:
    #   before:
    #     deployments: rpc-auth
  - command: minikube
    args:
      - addons
      - enable
      - ingress
    when:
      before:
        deployments: rpc-auth
vars:
  - name: CHAIN_NAME
    question: Name of the chain as passed to generate-constants
    default: "devspace"
    source: env
  - name: ACTION
    question: Mkchain action (create or invite)
    default: "create"
    source: env

# profiles:
#   - name: rpc-auth
