apiVersion: v1
data:
  CHAIN_PARAMS: |
    {
      "bootstrap_mutez": "{{ .Values.bootstrap_mutez }}",
      "bootstrap_peers": {{ toJson .Values.bootstrap_peers }},
      "chain_name": "{{ .Values.chain_name }}",
      "genesis_block": "{{ .Values.genesis_chain_id }}",
      "timestamp": "{{ .Values.bootstrap_timestamp }}",
      "zerotier_in_use": {{ .Values.zerotier_in_use }}
    }
kind: ConfigMap
metadata:
  name: tezos-config
  namespace: tqtezos
---
apiVersion: v1
data:
  CHAIN_NAME: "{{ .Values.chain_name }}"
  NETWORK_ID: "{{ .Values.zerotier_network }}"
  ZTAUTHTOKEN: "{{ .Values.zerotier_token }}"
kind: ConfigMap
metadata:
  name: zerotier-config
  namespace: tqtezos
---
apiVersion: v1
data:
{{- if .Values.is_invitation }}
  KEYS_TYPE: cHVibGlj
{{- else }}
  KEYS_TYPE: c2VjcmV0
{{- end }}
{{ toYaml .Values.keys | indent 2}}
kind: Secret
metadata:
  name: tezos-secret
  namespace: tqtezos
